import { Airport, Adjacencia, Rota, Companhia } from "./types";

export const AIRPORTS: Airport[] = [
  // ── Norte ───────────────────────────────────────────────────
  { iata: "MAO", cidade: "Manaus",       estado: "AM", regiao: "Norte",        lat: -3.039,  lon: -60.050 },
  { iata: "BEL", cidade: "Belém",        estado: "PA", regiao: "Norte",        lat: -1.379,  lon: -48.479 },
  { iata: "PVH", cidade: "Porto Velho",  estado: "RO", regiao: "Norte",        lat: -8.709,  lon: -63.902 },
  { iata: "RBR", cidade: "Rio Branco",   estado: "AC", regiao: "Norte",        lat: -9.869,  lon: -67.898 },
  { iata: "BVB", cidade: "Boa Vista",    estado: "RR", regiao: "Norte",        lat:  2.841,  lon: -60.692 },
  { iata: "MCP", cidade: "Macapá",       estado: "AP", regiao: "Norte",        lat:  0.051,  lon: -51.072 },
  { iata: "PMW", cidade: "Palmas",       estado: "TO", regiao: "Norte",        lat:-10.291,  lon: -48.356 },
  { iata: "STM", cidade: "Santarém",     estado: "PA", regiao: "Norte",        lat: -2.422,  lon: -54.786 },
  { iata: "MAB", cidade: "Marabá",       estado: "PA", regiao: "Norte",        lat: -5.369,  lon: -49.138 },
  // ── Nordeste ────────────────────────────────────────────────
  { iata: "SLZ", cidade: "São Luís",           estado: "MA", regiao: "Nordeste", lat: -2.585,  lon: -44.234 },
  { iata: "IMP", cidade: "Imperatriz",          estado: "MA", regiao: "Nordeste", lat: -5.531,  lon: -47.459 },
  { iata: "THE", cidade: "Teresina",            estado: "PI", regiao: "Nordeste", lat: -5.059,  lon: -42.824 },
  { iata: "PHB", cidade: "Parnaíba",            estado: "PI", regiao: "Nordeste", lat: -2.893,  lon: -41.733 },
  { iata: "FOR", cidade: "Fortaleza",           estado: "CE", regiao: "Nordeste", lat: -3.776,  lon: -38.532 },
  { iata: "JDO", cidade: "Juazeiro do Norte",   estado: "CE", regiao: "Nordeste", lat: -7.219,  lon: -39.270 },
  { iata: "NAT", cidade: "Natal",               estado: "RN", regiao: "Nordeste", lat: -5.768,  lon: -35.376 },
  { iata: "JPA", cidade: "João Pessoa",         estado: "PB", regiao: "Nordeste", lat: -7.146,  lon: -34.950 },
  { iata: "CPV", cidade: "Campina Grande",      estado: "PB", regiao: "Nordeste", lat: -7.269,  lon: -35.897 },
  { iata: "REC", cidade: "Recife",              estado: "PE", regiao: "Nordeste", lat: -8.126,  lon: -34.923 },
  { iata: "MCZ", cidade: "Maceió",              estado: "AL", regiao: "Nordeste", lat: -9.511,  lon: -35.792 },
  { iata: "AJU", cidade: "Aracaju",             estado: "SE", regiao: "Nordeste", lat:-10.984,  lon: -37.070 },
  { iata: "SSA", cidade: "Salvador",            estado: "BA", regiao: "Nordeste", lat:-12.909,  lon: -38.325 },
  { iata: "VDC", cidade: "Vitória da Conquista",estado: "BA", regiao: "Nordeste", lat:-14.862,  lon: -40.863 },
  { iata: "BPS", cidade: "Porto Seguro",        estado: "BA", regiao: "Nordeste", lat:-16.439,  lon: -39.080 },
  { iata: "IOS", cidade: "Ilhéus",              estado: "BA", regiao: "Nordeste", lat:-14.816,  lon: -39.033 },
  // ── Centro-Oeste ────────────────────────────────────────────
  { iata: "BSB", cidade: "Brasília",      estado: "DF", regiao: "Centro-Oeste", lat:-15.869,  lon: -47.921 },
  { iata: "GYN", cidade: "Goiânia",       estado: "GO", regiao: "Centro-Oeste", lat:-16.632,  lon: -49.220 },
  { iata: "CGB", cidade: "Cuiabá",        estado: "MT", regiao: "Centro-Oeste", lat:-15.653,  lon: -56.117 },
  { iata: "CGR", cidade: "Campo Grande",  estado: "MS", regiao: "Centro-Oeste", lat:-20.469,  lon: -54.671 },
  { iata: "ROO", cidade: "Rondonópolis",  estado: "MT", regiao: "Centro-Oeste", lat:-16.586,  lon: -54.724 },
  // ── Sudeste ─────────────────────────────────────────────────
  { iata: "GRU", cidade: "São Paulo",          estado: "SP", regiao: "Sudeste", lat:-23.432,  lon: -46.469 },
  { iata: "CGH", cidade: "São Paulo (Congonhas)", estado: "SP", regiao: "Sudeste", lat:-23.627, lon: -46.656 },
  { iata: "VCP", cidade: "Campinas",           estado: "SP", regiao: "Sudeste", lat:-23.007,  lon: -47.135 },
  { iata: "GIG", cidade: "Rio de Janeiro",     estado: "RJ", regiao: "Sudeste", lat:-22.810,  lon: -43.250 },
  { iata: "SDU", cidade: "Rio de Janeiro (SDU)",estado: "RJ", regiao: "Sudeste", lat:-22.910,  lon: -43.163 },
  { iata: "CNF", cidade: "Belo Horizonte",     estado: "MG", regiao: "Sudeste", lat:-19.633,  lon: -43.972 },
  { iata: "PLU", cidade: "Belo Horizonte (Pampulha)", estado: "MG", regiao: "Sudeste", lat:-19.851, lon: -43.950 },
  { iata: "VIX", cidade: "Vitória",            estado: "ES", regiao: "Sudeste", lat:-20.258,  lon: -40.286 },
  { iata: "UDI", cidade: "Uberlândia",         estado: "MG", regiao: "Sudeste", lat:-18.882,  lon: -48.225 },
  { iata: "MOC", cidade: "Montes Claros",      estado: "MG", regiao: "Sudeste", lat:-16.707,  lon: -43.819 },
  { iata: "IZA", cidade: "Juiz de Fora",       estado: "MG", regiao: "Sudeste", lat:-21.511,  lon: -43.173 },
  { iata: "SJP", cidade: "São José do Rio Preto", estado: "SP", regiao: "Sudeste", lat:-20.816, lon: -49.395 },
  { iata: "RAO", cidade: "Ribeirão Preto",     estado: "SP", regiao: "Sudeste", lat:-21.134,  lon: -47.777 },
  { iata: "BAU", cidade: "Bauru",              estado: "SP", regiao: "Sudeste", lat:-22.345,  lon: -49.054 },
  { iata: "PPB", cidade: "Presidente Prudente",estado: "SP", regiao: "Sudeste", lat:-22.185,  lon: -51.424 },
  // ── Sul ─────────────────────────────────────────────────────
  { iata: "CWB", cidade: "Curitiba",        estado: "PR", regiao: "Sul", lat:-25.528,  lon: -49.176 },
  { iata: "FLN", cidade: "Florianópolis",   estado: "SC", regiao: "Sul", lat:-27.671,  lon: -48.548 },
  { iata: "POA", cidade: "Porto Alegre",    estado: "RS", regiao: "Sul", lat:-29.994,  lon: -51.171 },
  { iata: "LDB", cidade: "Londrina",        estado: "PR", regiao: "Sul", lat:-23.334,  lon: -51.130 },
  { iata: "MGF", cidade: "Maringá",         estado: "PR", regiao: "Sul", lat:-23.476,  lon: -52.016 },
  { iata: "JOI", cidade: "Joinville",       estado: "SC", regiao: "Sul", lat:-26.224,  lon: -48.798 },
  { iata: "NVT", cidade: "Navegantes",      estado: "SC", regiao: "Sul", lat:-26.879,  lon: -48.651 },
  { iata: "IGU", cidade: "Foz do Iguaçu",  estado: "PR", regiao: "Sul", lat:-25.600,  lon: -54.487 },
  { iata: "PFB", cidade: "Passo Fundo",     estado: "RS", regiao: "Sul", lat:-28.243,  lon: -52.327 },
];

const L: Companhia[] = ["LATAM"];
const G: Companhia[] = ["GOL"];
const A: Companhia[] = ["Azul"];
const P: Companhia[] = ["Passaredo"];
const LG: Companhia[] = ["LATAM", "GOL"];
const LA: Companhia[] = ["LATAM", "Azul"];
const GA: Companhia[] = ["GOL", "Azul"];
const LGA: Companhia[] = ["LATAM", "GOL", "Azul"];

export const ADJACENCIAS: Adjacencia[] = [
  // ── GRU hub ─────────────────────────────────────────────────
  { origem: "GRU", destino: "REC", tipo: "hub",            peso: 2.0, companhias: LG,  distancia_km: 2688 },
  { origem: "GRU", destino: "SSA", tipo: "hub",            peso: 2.0, companhias: LGA, distancia_km: 1959 },
  { origem: "GRU", destino: "FOR", tipo: "hub",            peso: 2.0, companhias: LGA, distancia_km: 2803 },
  { origem: "GRU", destino: "NAT", tipo: "hub",            peso: 2.0, companhias: LG,  distancia_km: 2717 },
  { origem: "GRU", destino: "SLZ", tipo: "hub",            peso: 2.0, companhias: LGA, distancia_km: 2600 },
  { origem: "GRU", destino: "BSB", tipo: "hub",            peso: 2.0, companhias: LGA, distancia_km:  873 },
  { origem: "GRU", destino: "GYN", tipo: "hub",            peso: 2.0, companhias: LGA, distancia_km: 1020 },
  { origem: "GRU", destino: "CNF", tipo: "hub",            peso: 2.0, companhias: LGA, distancia_km:  586 },
  { origem: "GRU", destino: "GIG", tipo: "hub",            peso: 2.0, companhias: LGA, distancia_km:  357 },
  { origem: "GRU", destino: "VIX", tipo: "hub",            peso: 2.0, companhias: L,   distancia_km:  876 },
  { origem: "GRU", destino: "CWB", tipo: "hub",            peso: 2.0, companhias: LGA, distancia_km:  408 },
  { origem: "GRU", destino: "FLN", tipo: "hub",            peso: 2.0, companhias: LGA, distancia_km:  692 },
  { origem: "GRU", destino: "POA", tipo: "hub",            peso: 2.0, companhias: LGA, distancia_km: 1111 },
  { origem: "GRU", destino: "MAO", tipo: "hub",            peso: 2.0, companhias: LGA, distancia_km: 2700 },
  { origem: "GRU", destino: "BEL", tipo: "hub",            peso: 2.0, companhias: LGA, distancia_km: 2519 },
  { origem: "GRU", destino: "PVH", tipo: "hub",            peso: 2.0, companhias: A,   distancia_km: 2867 },
  { origem: "GRU", destino: "IGU", tipo: "hub",            peso: 2.0, companhias: LA,  distancia_km:  985 },
  { origem: "GRU", destino: "CGB", tipo: "hub",            peso: 2.0, companhias: GA,  distancia_km: 1593 },
  { origem: "GRU", destino: "CGR", tipo: "hub",            peso: 2.0, companhias: GA,  distancia_km: 1025 },
  { origem: "GRU", destino: "MCZ", tipo: "hub",            peso: 2.0, companhias: LG,  distancia_km: 2270 },
  { origem: "GRU", destino: "THE", tipo: "hub",            peso: 2.0, companhias: A,   distancia_km: 2499 },
  { origem: "GRU", destino: "UDI", tipo: "hub",            peso: 2.0, companhias: A,   distancia_km:  826 },
  { origem: "GRU", destino: "MOC", tipo: "hub",            peso: 2.0, companhias: A,   distancia_km:  860 },
  { origem: "GRU", destino: "RAO", tipo: "hub",            peso: 2.0, companhias: A,   distancia_km:  313 },
  { origem: "GRU", destino: "SJP", tipo: "hub",            peso: 2.0, companhias: A,   distancia_km:  430 },
  { origem: "GRU", destino: "BAU", tipo: "hub",            peso: 2.0, companhias: A,   distancia_km:  323 },
  { origem: "GRU", destino: "PPB", tipo: "hub",            peso: 2.0, companhias: A,   distancia_km:  585 },
  // ── GIG hub ─────────────────────────────────────────────────
  { origem: "GIG", destino: "BSB", tipo: "hub",            peso: 2.0, companhias: LG,  distancia_km: 1157 },
  { origem: "GIG", destino: "CNF", tipo: "hub",            peso: 2.0, companhias: LG,  distancia_km:  434 },
  { origem: "GIG", destino: "FOR", tipo: "hub",            peso: 2.0, companhias: LG,  distancia_km: 2808 },
  { origem: "GIG", destino: "REC", tipo: "hub",            peso: 2.0, companhias: LG,  distancia_km: 2356 },
  { origem: "GIG", destino: "SSA", tipo: "hub",            peso: 2.0, companhias: LG,  distancia_km: 1673 },
  { origem: "GIG", destino: "CWB", tipo: "hub",            peso: 2.0, companhias: LG,  distancia_km:  852 },
  { origem: "GIG", destino: "POA", tipo: "hub",            peso: 2.0, companhias: LG,  distancia_km: 1497 },
  { origem: "GIG", destino: "FLN", tipo: "hub",            peso: 2.0, companhias: L,   distancia_km: 1049 },
  { origem: "GIG", destino: "VIX", tipo: "hub",            peso: 2.0, companhias: L,   distancia_km:  520 },
  // ── CGH hub ─────────────────────────────────────────────────
  { origem: "CGH", destino: "BSB", tipo: "hub",            peso: 2.0, companhias: LG,  distancia_km:  873 },
  { origem: "CGH", destino: "CWB", tipo: "hub",            peso: 2.0, companhias: LG,  distancia_km:  408 },
  { origem: "CGH", destino: "FLN", tipo: "hub",            peso: 2.0, companhias: LG,  distancia_km:  692 },
  { origem: "CGH", destino: "POA", tipo: "hub",            peso: 2.0, companhias: LG,  distancia_km: 1111 },
  { origem: "CGH", destino: "GIG", tipo: "hub",            peso: 2.0, companhias: LG,  distancia_km:  357 },
  { origem: "CGH", destino: "CNF", tipo: "hub",            peso: 2.0, companhias: LG,  distancia_km:  586 },
  { origem: "CGH", destino: "FOR", tipo: "hub",            peso: 2.0, companhias: G,   distancia_km: 2803 },
  { origem: "CGH", destino: "SSA", tipo: "hub",            peso: 2.0, companhias: G,   distancia_km: 1959 },
  // ── BSB hub ─────────────────────────────────────────────────
  { origem: "BSB", destino: "REC", tipo: "hub",            peso: 2.0, companhias: LG,  distancia_km: 1851 },
  { origem: "BSB", destino: "SSA", tipo: "hub",            peso: 2.0, companhias: LG,  distancia_km: 1194 },
  { origem: "BSB", destino: "FOR", tipo: "hub",            peso: 2.0, companhias: LG,  distancia_km: 2166 },
  { origem: "BSB", destino: "NAT", tipo: "hub",            peso: 2.0, companhias: G,   distancia_km: 1800 },
  { origem: "BSB", destino: "MCZ", tipo: "hub",            peso: 2.0, companhias: G,   distancia_km: 1617 },
  { origem: "BSB", destino: "SLZ", tipo: "hub",            peso: 2.0, companhias: G,   distancia_km: 1090 },
  { origem: "BSB", destino: "THE", tipo: "hub",            peso: 2.0, companhias: G,   distancia_km: 1089 },
  { origem: "BSB", destino: "MAO", tipo: "hub",            peso: 2.0, companhias: LG,  distancia_km: 2236 },
  { origem: "BSB", destino: "BEL", tipo: "hub",            peso: 2.0, companhias: LG,  distancia_km: 1970 },
  { origem: "BSB", destino: "CWB", tipo: "hub",            peso: 2.0, companhias: L,   distancia_km: 1405 },
  { origem: "BSB", destino: "FLN", tipo: "hub",            peso: 2.0, companhias: L,   distancia_km: 1663 },
  { origem: "BSB", destino: "POA", tipo: "hub",            peso: 2.0, companhias: LG,  distancia_km: 1987 },
  { origem: "BSB", destino: "CGB", tipo: "hub",            peso: 2.0, companhias: G,   distancia_km: 1137 },
  { origem: "BSB", destino: "CGR", tipo: "hub",            peso: 2.0, companhias: G,   distancia_km: 1129 },
  { origem: "BSB", destino: "GYN", tipo: "regional",       peso: 1.0, companhias: LG,  distancia_km:  209 },
  { origem: "BSB", destino: "CNF", tipo: "hub",            peso: 2.0, companhias: L,   distancia_km:  716 },
  { origem: "BSB", destino: "PMW", tipo: "hub",            peso: 2.0, companhias: L,   distancia_km:  975 },
  { origem: "BSB", destino: "MAB", tipo: "hub",            peso: 2.0, companhias: G,   distancia_km:  990 },
  // ── VCP hub (Azul) ──────────────────────────────────────────
  { origem: "VCP", destino: "REC", tipo: "hub",            peso: 2.0, companhias: A,   distancia_km: 2688 },
  { origem: "VCP", destino: "SSA", tipo: "hub",            peso: 2.0, companhias: A,   distancia_km: 1959 },
  { origem: "VCP", destino: "FOR", tipo: "hub",            peso: 2.0, companhias: A,   distancia_km: 2803 },
  { origem: "VCP", destino: "MAO", tipo: "hub",            peso: 2.0, companhias: A,   distancia_km: 2700 },
  { origem: "VCP", destino: "BEL", tipo: "hub",            peso: 2.0, companhias: A,   distancia_km: 2519 },
  { origem: "VCP", destino: "BVB", tipo: "hub",            peso: 2.0, companhias: A,   distancia_km: 3022 },
  { origem: "VCP", destino: "CWB", tipo: "hub",            peso: 2.0, companhias: A,   distancia_km:  408 },
  { origem: "VCP", destino: "FLN", tipo: "hub",            peso: 2.0, companhias: A,   distancia_km:  692 },
  { origem: "VCP", destino: "POA", tipo: "hub",            peso: 2.0, companhias: A,   distancia_km: 1111 },
  { origem: "VCP", destino: "LDB", tipo: "hub",            peso: 2.0, companhias: A,   distancia_km:  412 },
  { origem: "VCP", destino: "MGF", tipo: "hub",            peso: 2.0, companhias: A,   distancia_km:  472 },
  { origem: "VCP", destino: "IGU", tipo: "hub",            peso: 2.0, companhias: A,   distancia_km:  985 },
  { origem: "VCP", destino: "CGB", tipo: "hub",            peso: 2.0, companhias: A,   distancia_km: 1593 },
  { origem: "VCP", destino: "CGR", tipo: "hub",            peso: 2.0, companhias: A,   distancia_km: 1025 },
  { origem: "VCP", destino: "BSB", tipo: "hub",            peso: 2.0, companhias: A,   distancia_km:  873 },
  { origem: "VCP", destino: "MCP", tipo: "hub",            peso: 2.0, companhias: A,   distancia_km: 2625 },
  { origem: "VCP", destino: "NAT", tipo: "hub",            peso: 2.0, companhias: A,   distancia_km: 2717 },
  { origem: "VCP", destino: "MCZ", tipo: "hub",            peso: 2.0, companhias: A,   distancia_km: 2270 },
  // ── Nordeste regional ────────────────────────────────────────
  { origem: "REC", destino: "SSA", tipo: "regional",       peso: 1.0, companhias: LG,  distancia_km:  834 },
  { origem: "REC", destino: "FOR", tipo: "regional",       peso: 1.0, companhias: LG,  distancia_km:  800 },
  { origem: "REC", destino: "NAT", tipo: "regional",       peso: 1.0, companhias: L,   distancia_km:  290 },
  { origem: "REC", destino: "JPA", tipo: "regional",       peso: 1.0, companhias: L,   distancia_km:  120 },
  { origem: "REC", destino: "MCZ", tipo: "regional",       peso: 1.0, companhias: L,   distancia_km:  257 },
  { origem: "REC", destino: "AJU", tipo: "regional",       peso: 1.0, companhias: L,   distancia_km:  510 },
  { origem: "SSA", destino: "FOR", tipo: "regional",       peso: 1.0, companhias: LG,  distancia_km: 1234 },
  { origem: "SSA", destino: "MCZ", tipo: "regional",       peso: 1.0, companhias: L,   distancia_km:  340 },
  { origem: "SSA", destino: "AJU", tipo: "regional",       peso: 1.0, companhias: L,   distancia_km:  358 },
  { origem: "SSA", destino: "IOS", tipo: "regional",       peso: 1.0, companhias: A,   distancia_km:  460 },
  { origem: "SSA", destino: "BPS", tipo: "regional",       peso: 1.0, companhias: A,   distancia_km:  450 },
  { origem: "SSA", destino: "VDC", tipo: "regional",       peso: 1.0, companhias: A,   distancia_km:  520 },
  { origem: "FOR", destino: "NAT", tipo: "regional",       peso: 1.0, companhias: LG,  distancia_km:  520 },
  { origem: "FOR", destino: "JPA", tipo: "regional",       peso: 1.0, companhias: L,   distancia_km:  620 },
  { origem: "FOR", destino: "THE", tipo: "regional",       peso: 1.0, companhias: G,   distancia_km:  623 },
  { origem: "FOR", destino: "JDO", tipo: "regional",       peso: 1.0, companhias: A,   distancia_km:  500 },
  { origem: "FOR", destino: "SLZ", tipo: "regional",       peso: 1.0, companhias: L,   distancia_km: 1014 },
  { origem: "NAT", destino: "JPA", tipo: "regional",       peso: 1.0, companhias: L,   distancia_km:  200 },
  { origem: "NAT", destino: "JDO", tipo: "regional",       peso: 1.0, companhias: A,   distancia_km:  550 },
  { origem: "JPA", destino: "CPV", tipo: "regional",       peso: 1.0, companhias: P,   distancia_km:  129 },
  { origem: "THE", destino: "SLZ", tipo: "regional",       peso: 1.0, companhias: L,   distancia_km:  462 },
  { origem: "THE", destino: "IMP", tipo: "regional",       peso: 1.0, companhias: P,   distancia_km:  350 },
  { origem: "SLZ", destino: "IMP", tipo: "regional",       peso: 1.0, companhias: P,   distancia_km:  400 },
  { origem: "SLZ", destino: "PHB", tipo: "regional",       peso: 1.0, companhias: P,   distancia_km:  420 },
  // ── Norte regional ──────────────────────────────────────────
  { origem: "MAO", destino: "BEL", tipo: "regional",       peso: 1.0, companhias: LGA, distancia_km: 1687 },
  { origem: "MAO", destino: "PVH", tipo: "regional",       peso: 1.0, companhias: A,   distancia_km:  897 },
  { origem: "MAO", destino: "BVB", tipo: "regional",       peso: 1.0, companhias: A,   distancia_km:  783 },
  { origem: "MAO", destino: "STM", tipo: "regional",       peso: 1.0, companhias: A,   distancia_km:  895 },
  { origem: "BEL", destino: "MAB", tipo: "regional",       peso: 1.0, companhias: A,   distancia_km:  590 },
  { origem: "BEL", destino: "STM", tipo: "regional",       peso: 1.0, companhias: A,   distancia_km:  762 },
  { origem: "BEL", destino: "MCP", tipo: "regional",       peso: 1.0, companhias: A,   distancia_km:  325 },
  { origem: "BEL", destino: "SLZ", tipo: "inter-regional", peso: 2.5, companhias: LG,  distancia_km:  484 },
  { origem: "BEL", destino: "IMP", tipo: "inter-regional", peso: 2.5, companhias: P,   distancia_km:  600 },
  { origem: "PVH", destino: "RBR", tipo: "regional",       peso: 1.0, companhias: P,   distancia_km:  523 },
  { origem: "BVB", destino: "MCP", tipo: "regional",       peso: 1.0, companhias: A,   distancia_km:  783 },
  { origem: "PMW", destino: "MAB", tipo: "regional",       peso: 1.0, companhias: A,   distancia_km:  600 },
  { origem: "PMW", destino: "BEL", tipo: "inter-regional", peso: 2.5, companhias: G,   distancia_km:  960 },
  // ── Centro-Oeste regional ────────────────────────────────────
  { origem: "BSB", destino: "CGB", tipo: "inter-regional", peso: 2.5, companhias: G,   distancia_km: 1137 },
  { origem: "CGB", destino: "CGR", tipo: "regional",       peso: 1.0, companhias: A,   distancia_km:  615 },
  { origem: "CGB", destino: "ROO", tipo: "regional",       peso: 1.0, companhias: P,   distancia_km:  213 },
  { origem: "GYN", destino: "CGB", tipo: "regional",       peso: 1.0, companhias: A,   distancia_km: 1003 },
  { origem: "GYN", destino: "CGR", tipo: "regional",       peso: 1.0, companhias: A,   distancia_km:  883 },
  // ── Sudeste regional ─────────────────────────────────────────
  { origem: "CNF", destino: "VIX", tipo: "regional",       peso: 1.0, companhias: L,   distancia_km:  517 },
  { origem: "CNF", destino: "IZA", tipo: "regional",       peso: 1.0, companhias: A,   distancia_km:  221 },
  { origem: "CNF", destino: "MOC", tipo: "regional",       peso: 1.0, companhias: P,   distancia_km:  432 },
  { origem: "CNF", destino: "UDI", tipo: "regional",       peso: 1.0, companhias: A,   distancia_km:  541 },
  { origem: "GIG", destino: "IZA", tipo: "regional",       peso: 1.0, companhias: A,   distancia_km:  177 },
  { origem: "VIX", destino: "IZA", tipo: "regional",       peso: 1.0, companhias: P,   distancia_km:  259 },
  { origem: "SDU", destino: "CNF", tipo: "regional",       peso: 1.0, companhias: LG,  distancia_km:  434 },
  { origem: "SDU", destino: "VIX", tipo: "regional",       peso: 1.0, companhias: L,   distancia_km:  520 },
  { origem: "SDU", destino: "IZA", tipo: "regional",       peso: 1.0, companhias: A,   distancia_km:  177 },
  { origem: "PLU", destino: "GIG", tipo: "regional",       peso: 1.0, companhias: LG,  distancia_km:  434 },
  { origem: "PLU", destino: "BSB", tipo: "regional",       peso: 1.0, companhias: L,   distancia_km:  716 },
  // ── Sul regional ─────────────────────────────────────────────
  { origem: "CWB", destino: "FLN", tipo: "regional",       peso: 1.0, companhias: LG,  distancia_km:  303 },
  { origem: "CWB", destino: "POA", tipo: "regional",       peso: 1.0, companhias: LG,  distancia_km:  703 },
  { origem: "FLN", destino: "POA", tipo: "regional",       peso: 1.0, companhias: LG,  distancia_km:  462 },
  { origem: "CWB", destino: "LDB", tipo: "regional",       peso: 1.0, companhias: A,   distancia_km:  140 },
  { origem: "CWB", destino: "MGF", tipo: "regional",       peso: 1.0, companhias: A,   distancia_km:  122 },
  { origem: "CWB", destino: "JOI", tipo: "regional",       peso: 1.0, companhias: A,   distancia_km:  120 },
  { origem: "CWB", destino: "NVT", tipo: "regional",       peso: 1.0, companhias: A,   distancia_km:  160 },
  { origem: "CWB", destino: "IGU", tipo: "regional",       peso: 1.0, companhias: A,   distancia_km:  585 },
  { origem: "FLN", destino: "JOI", tipo: "regional",       peso: 1.0, companhias: P,   distancia_km:   88 },
  { origem: "FLN", destino: "NVT", tipo: "regional",       peso: 1.0, companhias: P,   distancia_km:   94 },
  { origem: "POA", destino: "PFB", tipo: "regional",       peso: 1.0, companhias: P,   distancia_km:  216 },
  { origem: "LDB", destino: "MGF", tipo: "regional",       peso: 1.0, companhias: P,   distancia_km:   89 },
  // ── Inter-regionais ──────────────────────────────────────────
  { origem: "VIX", destino: "SSA", tipo: "inter-regional", peso: 2.5, companhias: L,   distancia_km:  850 },
  { origem: "MOC", destino: "BSB", tipo: "inter-regional", peso: 2.5, companhias: P,   distancia_km:  655 },
  { origem: "JDO", destino: "REC", tipo: "inter-regional", peso: 2.5, companhias: A,   distancia_km:  630 },
  { origem: "CPV", destino: "REC", tipo: "inter-regional", peso: 2.5, companhias: P,   distancia_km:  180 },
  { origem: "PHB", destino: "THE", tipo: "inter-regional", peso: 2.5, companhias: P,   distancia_km:  290 },
];

export const ROTAS_OBRIGATORIAS: Rota[] = [
  { origem: "REC", destino: "POA" },
  { origem: "MAO", destino: "GRU" },
  { origem: "FOR", destino: "FLN" },
  { origem: "BEL", destino: "CNF" },
  { origem: "NAT", destino: "CWB" },
  { origem: "RBR", destino: "GIG" },
  { origem: "THE", destino: "POA" },
];

export const REGION_COLORS: Record<string, string> = {
  Nordeste:       "#f97316",
  Sudeste:        "#3b82f6",
  "Centro-Oeste": "#eab308",
  Sul:            "#22c55e",
  Norte:          "#a855f7",
};

export const AIRLINE_COLORS: Record<string, string> = {
  LATAM:      "#e11d48",
  GOL:        "#f97316",
  Azul:       "#3b82f6",
  Passaredo:  "#10b981",
};

export const AIRPORT_MAP = new Map(AIRPORTS.map((a) => [a.iata, a]));
